// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APISuperHeroi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240119063559_'dadosSuperpoderes'")]
    partial class dadosSuperpoderes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APISuperHeroi.Model.Heroi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("Altura")
                        .HasColumnType("double");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeHeroi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("Peso")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Herois");
                });

            modelBuilder.Entity("APISuperHeroi.Model.HeroisSuperPoderes", b =>
                {
                    b.Property<int>("HeroiId")
                        .HasColumnType("int");

                    b.Property<int>("SuperPoderesId")
                        .HasColumnType("int");

                    b.HasKey("HeroiId", "SuperPoderesId");

                    b.HasIndex("SuperPoderesId");

                    b.ToTable("HeroisSuperPoderes");
                });

            modelBuilder.Entity("APISuperHeroi.Model.SuperPoderes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("SuperPoder")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SuperPoderes");
                });

            modelBuilder.Entity("APISuperHeroi.Model.HeroisSuperPoderes", b =>
                {
                    b.HasOne("APISuperHeroi.Model.Heroi", "Heroi")
                        .WithMany("HeroisSuperPoderes")
                        .HasForeignKey("HeroiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APISuperHeroi.Model.SuperPoderes", "SuperPoder")
                        .WithMany()
                        .HasForeignKey("SuperPoderesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroi");

                    b.Navigation("SuperPoder");
                });

            modelBuilder.Entity("APISuperHeroi.Model.Heroi", b =>
                {
                    b.Navigation("HeroisSuperPoderes");
                });
#pragma warning restore 612, 618
        }
    }
}
